<?php

namespace Tests\Services;

use App\Services\IUserService;
use Tests\TestCase;

class UserServiceTest extends TestCase
{
    private IUserService $userService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userService = $this->app->make(IUserService::class);
    }

    public function testSetUp()
    {
        self::assertTrue(true);
    }

    public function testLoginSuccess()
    {
        $login = $this->userService->login('utifmd', 'rahasia');

        self::assertTrue($login);
    }

    public function testLoginUserNotFound()
    {
        $login = $this->userService->login('utif', 'rahasia');

        self::assertFalse($login);
    }

    public function testLoginUserWrongPassword()
    {
        $login = $this->userService->login('utifmd', 'rahas');

        self::assertFalse($login);
    }

}
